project:
  type: website

website:
  title: "DSS Project Lab 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Project Stages"
        menu:
          - text: "1. Data Sourcing"
            file: 1-Data-Sourcing/Data-Sourcing.ipynb
          - text: "2. Preliminary EDA"
            file: 2-Preliminary-EDA/Preliminary-EDA.ipynb
          - text: "3. Data Wrangling"
            file: 3-Data-Wrangling/Data-Wrangling.ipynb
          - text: "4. Preprocessing"
            file: 4-Data-preprocessing/Data-Preprocessing.ipynb
          - text: "5. Predictive Modelling"
            file: 5-Predictive Modelling/Predictive_modelling.ipynb
      - text: "Full Project"
        file: Full-Project/*.ipynb

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true